<?php
  $dictionary["Project"]["fields"]['account_name'] =
    array (
        'inline_edit' => false,
        'required' => false,
        'source' => 'non-db',
        'name' => 'account_name',
        'vname' => 'LBL_ACCOUNT_NAME',
        'type' => 'relate',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'account_id',
        'ext2' => 'Accounts',
        'module' => 'Accounts',
        'rname' => 'name',
        'quicksearch' => 'enabled',
        'studio' => 'visible',
);
$dictionary["Project"]["fields"]['account_id'] =
    array (
        'inline_edit' => false,
        'required' => false,
        'name' => 'account_id',
        'vname' => 'LBL_ACCOUNT_ID',
        'type' => 'id',
        'massupdate' => '0',
        'default' => NULL,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '36',
        'size' => '20',
);
?>
